baseurl = "https://dazzling-poincare-b7ea5f.netlify.com"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "vec"
title = "miraglobal.com"
[[menu.main]]
name = "contact"
url = "/contact"
weight = 2
[[menu.main]]
name = "post"
url = "/post"
weight = 1
[params]
Avatar = "img/avatar.jpg"
Description = "There are some words to describe your site"
Email = "no@gmail.com"
FacebookID = "Your Facebook ID"
GithubID = "Your Github ID"
GoogleplusID = "Your Googleplus ID"
Keywords = "open source, education"
LinkedInID = "Your LinkedIn ID"
SelfIntro = "Open Source and Education"
TwitterID = "Your Twitter ID"
