baseurl = "https://dazzling-poincare-b7ea5f.netlify.com"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "vec"
title = "yii.im"
[[menu.main]]
name = "contact"
url = "/contact"
weight = 2
[[menu.main]]
name = "post"
url = "/post"
weight = 1
[params]
Avatar = "img/avatar.jpg"
Description = "There are some words to describe your site"
Email = "yiichou@gmail.com"
FacebookID = "Your Facebook ID"
GithubID = "Your Github ID"
GoogleplusID = "Your Googleplus ID"
Keywords = "key, 关键字, キーワード"
LinkedInID = "Your LinkedIn ID"
SelfIntro = "Just a worm, seek for true, live in shadow, no more..."
TwitterID = "Your Twitter ID"
