baseurl = "https://seazine.org/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "vec"
title = "miraglobal.com"
[[menu.main]]
name = "contact"
url = "/contact"
weight = 2
[[menu.main]]
name = "post"
url = "/post"
weight = 1
[params]
Avatar = "img/avatar.jpg"
Description = "Open source and education"
Email = "no@gmail.com"

Keywords = "open source, education"

SelfIntro = "Open Source and Education"
TwitterID = "Your Twitter ID"
